#!/bin/bash
#
# Luan Nguyen
# tonguyen500@csu.fullerton.edu
# CPSC 254-99
#
#quickresizer
# A shell to resize images to 1024 width if it exceed 1024 pixels using Imagemagick
#

function usage () {
  echo "Usage:"
  echo "  ${1} parameter1 parameter2  parameter3..."
  echo
  echo "  Include at least one parameter and the script will loop through"
  echo "  each parameter, printing the parameter to stdout."
}

#
# Main
#
SCRIPTNAME=`basename ${0}`
MAXWIDTH=1024
if [ ${#} -lt 1 ]; then
  usage ${SCRIPTNAME}
fi

for PARAMETER in ${*}; do

  IMAGE=`identify ${PARAMETER} | cut -c 36-39`
  echo ${IMAGE}
  #IMAGE2='expr  $ZERO'
  if [ ${IMAGE} -gt ${MAXWIDTH} ]; then
  echo ${IMAGE}
  echo "${PARAMETER}"
  mogrify -resize 1024x ${PARAMETER}
  fi

done
